version: '3'

services:  

  redis:
    image: redis:latest
    hostname: redis

  web:
    build:
      context: .
      dockerfile: Dockerfile
    hostname: web
    command: ./scripts/run_app.sh
    volumes:
      - .:/app 
    ports:
      - "5000:5000"
    links:
      - redis

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: ./scripts/install_redis.sh
    command: ./scripts/run_redis.sh
    volumes:
      - .:/app
    links:
      - redis
    environment:
        - CELERY_BROKER=redis://redis:6379/0
        - CELERY_BACKEND=db+postgresql://postgres:123@localhost/mydatabase